package entities;
// Generated Jul 14, 2022, 12:41:47 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "jsf_hibernate_crud")
public class Client implements java.io.Serializable {

	private int userId;
	private String email;
	private String firstname;
	private String lastname;
	private String phone;
	private String gender;
	private Date age;
	private String clientcol;

	public Client() {
	}

	public Client(int userId) {
		this.userId = userId;
	}

	public Client(int userId, String email, String firstname, String lastname, String phone, String gender, Date age,
			String clientcol) {
		this.userId = userId;
		this.email = email;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.gender = gender;
		this.age = age;
		this.clientcol = clientcol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "email", length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "firstname", length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 100)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phone", length = 100)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "gender", length = 100)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "age", length = 10)
	public Date getAge() {
		return this.age;
	}

	public void setAge(Date age) {
		this.age = age;
	}

	@Column(name = "clientcol", length = 45)
	public String getClientcol() {
		return this.clientcol;
	}

	public void setClientcol(String clientcol) {
		this.clientcol = clientcol;
	}

}
